# Generated by Django 3.1 on 2020-08-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0003_auto_20200817_1922'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='language_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_constructor.languageslist'),
            preserve_default=False,
        ),
    ]
