# Generated by Django 3.1 on 2020-08-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileuser_language_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='language_list',
        ),
    ]
