# Generated by Django 3.1 on 2020-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profileuser_language_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(blank=True, default='Номер телефона', max_length=12),
        ),
    ]
