# Generated by Django 3.1 on 2020-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profileuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='about_you',
            field=models.TextField(blank=True, default='О себе'),
        ),
    ]
