# Generated by Django 3.1 on 2020-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profileuser_about_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='profile_icons/%Y%m%d/', verbose_name='Фото'),
        ),
    ]
