# Generated by Django 3.1 on 2020-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200820_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='linked_in',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
