# Generated by Django 3.1 on 2020-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, verbose_name='Название языка')),
                ('language_photo', models.ImageField(blank=True, upload_to='language_icon/%Y%m%d/', verbose_name='Иконки')),
            ],
        ),
    ]
