# Generated by Django 3.1 on 2020-08-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageslist',
            options={'verbose_name': 'Список языков', 'verbose_name_plural': 'Список языков'},
        ),
    ]
